-- MySQL Script generated by MySQL Workbench
-- Wed Feb 13 10:59:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema expediente_fgk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema expediente_fgk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `expediente_fgk` DEFAULT CHARACTER SET utf8 ;
USE `expediente_fgk` ;

-- -----------------------------------------------------
-- Table `expediente_fgk`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`municipio` (
  `id_municipio` INT NOT NULL AUTO_INCREMENT,
  `id_departamento` INT NOT NULL,
  `municipio` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_municipio`),
  INDEX `fk-Depatamento-Municipio_idx` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk-Depatamento-Municipio`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `expediente_fgk`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`centro_educativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`centro_educativo` (
  `codigo_centro_educativo` INT NOT NULL,
  `nombre_centro_educativo` VARCHAR(75) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(30) NOT NULL,
  `id_municipio` INT NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`codigo_centro_educativo`),
  INDEX `fk-Municipio-CentroEscolar_idx` (`id_municipio` ASC) VISIBLE,
  CONSTRAINT `fk-Municipio-CentroEscolar`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `expediente_fgk`.`municipio` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`class` (
  `id_class` VARCHAR(10) NOT NULL COMMENT 'Class-2019',
  `anho_ingreso` YEAR(4) NOT NULL,
  `anho_egreso` YEAR(4) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id_class`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`alumno` (
  `carnet_alumno` VARCHAR(15) NOT NULL,
  `id_class` VARCHAR(10) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `foto` MEDIUMBLOB NULL,
  `telefono` VARCHAR(10) NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `id_municipio` INT NOT NULL,
  `email` VARCHAR(75) NULL,
  `contrasenha` VARCHAR(25) NULL,
  `codigo_centro_educativo` INT NOT NULL,
  `turno_educativo` VARCHAR(1) NOT NULL,
  `estado` BIT(1) NOT NULL,
  `observaciones` VARCHAR(250) NULL,
  PRIMARY KEY (`carnet_alumno`),
  INDEX `fk-Municipio-Alumno_idx` (`id_municipio` ASC) VISIBLE,
  INDEX `fk-CentroEducativo-Alumno_idx` (`codigo_centro_educativo` ASC) VISIBLE,
  INDEX `fk-Class-Alumno_idx` (`id_class` ASC) VISIBLE,
  CONSTRAINT `fk-Municipio-Alumno`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `expediente_fgk`.`municipio` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-CentroEducativo-Alumno`
    FOREIGN KEY (`codigo_centro_educativo`)
    REFERENCES `expediente_fgk`.`centro_educativo` (`codigo_centro_educativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Class-Alumno`
    FOREIGN KEY (`id_class`)
    REFERENCES `expediente_fgk`.`class` (`id_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`bitacora_alumno_centro_educativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`bitacora_alumno_centro_educativo` (
  `id_bitacora` INT NOT NULL AUTO_INCREMENT,
  `carnet_alumno` VARCHAR(15) NOT NULL,
  `codigo_centro_educativo` INT NOT NULL,
  `anho` YEAR(4) NOT NULL,
  `grado_cursado` VARCHAR(25) NOT NULL,
  `observaciones` VARCHAR(250) NULL,
  PRIMARY KEY (`id_bitacora`),
  INDEX `fk-Alumno-BitacoraCentroEducativo_idx` (`carnet_alumno` ASC) VISIBLE,
  INDEX `fk-CentroEducativo-BitacoraCentroEducativo_idx` (`codigo_centro_educativo` ASC) VISIBLE,
  CONSTRAINT `fk-Alumno-BitacoraCentroEducativo`
    FOREIGN KEY (`carnet_alumno`)
    REFERENCES `expediente_fgk`.`alumno` (`carnet_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-CentroEducativo-BitacoraCentroEducativo`
    FOREIGN KEY (`codigo_centro_educativo`)
    REFERENCES `expediente_fgk`.`centro_educativo` (`codigo_centro_educativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`ocupacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`ocupacion` (
  `id_ocupacion` INT NOT NULL AUTO_INCREMENT,
  `ocupacion` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id_ocupacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`tipo_responsable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`tipo_responsable` (
  `id_tipo_responsable` INT NOT NULL AUTO_INCREMENT,
  `tipo_responsable` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_responsable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`responsable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`responsable` (
  `dui` VARCHAR(10) NOT NULL,
  `carnet_alumno` VARCHAR(15) NOT NULL,
  `id_tipo_responsable` INT NOT NULL,
  `id_ocupacion` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `observaciones` VARCHAR(250) NULL,
  PRIMARY KEY (`dui`),
  INDEX `fk-Alumno-Responsable_idx` (`carnet_alumno` ASC) VISIBLE,
  INDEX `fk-TipoResponsable_idx` (`id_tipo_responsable` ASC) VISIBLE,
  INDEX `fk-Ocupacion_idx` (`id_ocupacion` ASC) VISIBLE,
  CONSTRAINT `fk-Alumno-Responsable`
    FOREIGN KEY (`carnet_alumno`)
    REFERENCES `expediente_fgk`.`alumno` (`carnet_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-TipoResponsable`
    FOREIGN KEY (`id_tipo_responsable`)
    REFERENCES `expediente_fgk`.`tipo_responsable` (`id_tipo_responsable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Ocupacion`
    FOREIGN KEY (`id_ocupacion`)
    REFERENCES `expediente_fgk`.`ocupacion` (`id_ocupacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`empleado` (
  `carnet_empleado` VARCHAR(15) NOT NULL,
  `id_cargo` INT NOT NULL,
  `dui` VARCHAR(11) NOT NULL,
  `nit` VARCHAR(17) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `telefono` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `id_municipio` INT NOT NULL,
  `observaciones` VARCHAR(250) NULL,
  PRIMARY KEY (`carnet_empleado`),
  INDEX `fk-Cargo-Empleado_idx` (`id_cargo` ASC) VISIBLE,
  INDEX `fk-Municipio-Empleado_idx` (`id_municipio` ASC) VISIBLE,
  CONSTRAINT `fk-Cargo-Empleado`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `expediente_fgk`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Municipio-Empleado`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `expediente_fgk`.`municipio` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`materia` (
  `id_materia` INT NOT NULL AUTO_INCREMENT,
  `nombre_materia` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`periodo` (
  `id_periodo` INT NOT NULL AUTO_INCREMENT,
  `nombre_periodo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id_periodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`grupo_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`grupo_materia` (
  `id_grupo_materia` VARCHAR(18) NOT NULL COMMENT 'C1-CLASS2019-MAT',
  `id_seccion` VARCHAR(14) NOT NULL,
  `id_materia` INT NOT NULL,
  `carnet_empleado` VARCHAR(15) NOT NULL,
  `anho` YEAR(4) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id_grupo_materia`),
  INDEX `fk-Materia-GrupoMateria_idx` (`id_materia` ASC) VISIBLE,
  INDEX `fk-Empleado-GrupoMateria_idx` (`carnet_empleado` ASC) VISIBLE,
  CONSTRAINT `fk-Materia-GrupoMateria`
    FOREIGN KEY (`id_materia`)
    REFERENCES `expediente_fgk`.`materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Empleado-GrupoMateria`
    FOREIGN KEY (`carnet_empleado`)
    REFERENCES `expediente_fgk`.`empleado` (`carnet_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`evaluaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`evaluaciones` (
  `id_evaluacion` INT NOT NULL COMMENT 'EV001-MAT-2019',
  `id_periodo` INT NOT NULL,
  `id_materia` INT NOT NULL,
  `nombre_evaluacion` VARCHAR(45) NOT NULL,
  `porcentaje` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`id_evaluacion`),
  INDEX `fk-Periodo-Evaluaciones_idx` (`id_periodo` ASC) VISIBLE,
  INDEX `fk-Materia-Evaluaciones_idx` (`id_materia` ASC) VISIBLE,
  CONSTRAINT `fk-Periodo-Evaluaciones`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `expediente_fgk`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Materia-Evaluaciones`
    FOREIGN KEY (`id_materia`)
    REFERENCES `expediente_fgk`.`materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`grado_mined`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`grado_mined` (
  `id_grado_mined` INT NOT NULL AUTO_INCREMENT,
  `grado_mined` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_grado_mined`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`notas_mined`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`notas_mined` (
  `id_notas_mined` INT NOT NULL AUTO_INCREMENT,
  `carnet_alumno` VARCHAR(15) NOT NULL,
  `id_periodo` INT NOT NULL,
  `id_materia` INT NOT NULL,
  `id_grado` INT NOT NULL,
  `nota` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`id_notas_mined`),
  INDEX `fk-Alumno-Mined_idx` (`carnet_alumno` ASC) VISIBLE,
  INDEX `fk-Materia-Mined_idx` (`id_materia` ASC) VISIBLE,
  INDEX `fk-Periodo-Mined_idx` (`id_periodo` ASC) VISIBLE,
  INDEX `fk-Grado-Mined_idx` (`id_grado` ASC) VISIBLE,
  CONSTRAINT `fk-Alumno-Mined`
    FOREIGN KEY (`carnet_alumno`)
    REFERENCES `expediente_fgk`.`alumno` (`carnet_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Materia-Mined`
    FOREIGN KEY (`id_materia`)
    REFERENCES `expediente_fgk`.`materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Periodo-Mined`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `expediente_fgk`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Grado-Mined`
    FOREIGN KEY (`id_grado`)
    REFERENCES `expediente_fgk`.`grado_mined` (`id_grado_mined`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`log_cambio_grupo_alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`log_cambio_grupo_alumno` (
  `carnet_alumno` VARCHAR(15) NOT NULL,
  `id_grupo_materia` VARCHAR(18) NOT NULL,
  `id_periodo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `observaciones` VARCHAR(250) NULL,
  PRIMARY KEY (`carnet_alumno`, `id_grupo_materia`, `id_periodo`),
  INDEX `fk-Grupo-Log_idx` (`id_grupo_materia` ASC) VISIBLE,
  INDEX `fk-Periodo-Log_idx` (`id_periodo` ASC) VISIBLE,
  CONSTRAINT `fk-Alumno-Log`
    FOREIGN KEY (`carnet_alumno`)
    REFERENCES `expediente_fgk`.`alumno` (`carnet_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Grupo-Log`
    FOREIGN KEY (`id_grupo_materia`)
    REFERENCES `expediente_fgk`.`grupo_materia` (`id_grupo_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Periodo-Log`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `expediente_fgk`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`log_cambio_grupo_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`log_cambio_grupo_docente` (
  `carnet_empleado` VARCHAR(15) NOT NULL,
  `id_grupo_materia` VARCHAR(18) NOT NULL,
  `id_periodo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `observaciones` VARCHAR(250) NULL,
  PRIMARY KEY (`carnet_empleado`, `id_grupo_materia`, `id_periodo`),
  INDEX `fk--GrupoMateria-Log_idx` (`id_grupo_materia` ASC) VISIBLE,
  INDEX `fk-Periodo-LogDocente_idx` (`id_periodo` ASC) VISIBLE,
  CONSTRAINT `fk-Empleado-Log`
    FOREIGN KEY (`carnet_empleado`)
    REFERENCES `expediente_fgk`.`empleado` (`carnet_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-GrupoMateria-Log`
    FOREIGN KEY (`id_grupo_materia`)
    REFERENCES `expediente_fgk`.`grupo_materia` (`id_grupo_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Periodo-LogDocente`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `expediente_fgk`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`criterio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`criterio` (
  `id_criterio` INT NOT NULL AUTO_INCREMENT,
  `nombre_criterio` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id_criterio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`aptitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`aptitud` (
  `id_aptitud` INT NOT NULL AUTO_INCREMENT,
  `id_criterio` INT NOT NULL,
  `nombre_aptitud` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id_aptitud`),
  INDEX `fk-Criterio-Aptitud_idx` (`id_criterio` ASC) VISIBLE,
  CONSTRAINT `fk-Criterio-Aptitud`
    FOREIGN KEY (`id_criterio`)
    REFERENCES `expediente_fgk`.`criterio` (`id_criterio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`seccion` (
  `id_seccion` VARCHAR(14) NOT NULL COMMENT 'C1-Class-2019',
  `id_class` VARCHAR(10) NOT NULL,
  `anho` YEAR(4) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id_seccion`),
  INDEX `fk-Class-Seccion_idx` (`id_class` ASC) VISIBLE,
  CONSTRAINT `fk-Class-Seccion`
    FOREIGN KEY (`id_class`)
    REFERENCES `expediente_fgk`.`class` (`id_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`alumno_seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`alumno_seccion` (
  `carnet_alumno` VARCHAR(15) NOT NULL,
  `id_seccion` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`carnet_alumno`, `id_seccion`),
  INDEX `fk-Seccion-Alumno_idx` (`id_seccion` ASC) VISIBLE,
  CONSTRAINT `fk-Alumno-Seccion`
    FOREIGN KEY (`carnet_alumno`)
    REFERENCES `expediente_fgk`.`alumno` (`carnet_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Seccion-Alumno`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `expediente_fgk`.`seccion` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`evaluaciones_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`evaluaciones_grupo` (
  `id_evaluaciones_grupo` VARCHAR(15) NOT NULL COMMENT 'C1-EV-MAT-2019',
  `id_evaluacion` INT NOT NULL,
  `id_grupo_materia` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`id_evaluaciones_grupo`),
  INDEX `fk-Evaluacion-Grupo_idx` (`id_evaluacion` ASC) VISIBLE,
  INDEX `fk-Grupo-Evaluacion_idx` (`id_grupo_materia` ASC) VISIBLE,
  CONSTRAINT `fk-Evaluacion-Grupo`
    FOREIGN KEY (`id_evaluacion`)
    REFERENCES `expediente_fgk`.`evaluaciones` (`id_evaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Grupo-Evaluacion`
    FOREIGN KEY (`id_grupo_materia`)
    REFERENCES `expediente_fgk`.`grupo_materia` (`id_grupo_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`notas_fgk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`notas_fgk` (
  `carnet_alumno` VARCHAR(15) NOT NULL,
  `id_evaluacion_grupo` VARCHAR(15) NOT NULL,
  `nota` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`carnet_alumno`),
  INDEX `fk-Evaluacion-Nota_idx` (`id_evaluacion_grupo` ASC) VISIBLE,
  CONSTRAINT `fk-Alumno-Nota`
    FOREIGN KEY (`carnet_alumno`)
    REFERENCES `expediente_fgk`.`alumno` (`carnet_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Evaluacion-Nota`
    FOREIGN KEY (`id_evaluacion_grupo`)
    REFERENCES `expediente_fgk`.`evaluaciones_grupo` (`id_evaluaciones_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`grupo_aptitudinal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`grupo_aptitudinal` (
  `id_grupo_aptitudinal` INT NOT NULL,
  `carnet_empleado` VARCHAR(15) NOT NULL,
  `id_periodo` INT NOT NULL,
  `id_seccion` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_grupo_aptitudinal`),
  INDEX `fk-Aptitud-Empleado_idx` (`carnet_empleado` ASC) VISIBLE,
  INDEX `fk-Aptitud-Periodo_idx` (`id_periodo` ASC) VISIBLE,
  INDEX `fk-Aptitud-Seccion_idx` (`id_seccion` ASC) VISIBLE,
  CONSTRAINT `fk-Aptitud-Empleado`
    FOREIGN KEY (`carnet_empleado`)
    REFERENCES `expediente_fgk`.`empleado` (`carnet_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Aptitud-Periodo`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `expediente_fgk`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Aptitud-Seccion`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `expediente_fgk`.`seccion` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_fgk`.`nota_aptitudinal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expediente_fgk`.`nota_aptitudinal` (
  `carnet_alumno` VARCHAR(15) NOT NULL,
  `carnet_docente` VARCHAR(14) NOT NULL,
  `id_periodo` INT NOT NULL,
  `id_aptitud` INT NOT NULL,
  `anho` YEAR(4) NOT NULL,
  `nota` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`carnet_alumno`, `anho`, `id_aptitud`, `id_periodo`, `carnet_docente`),
  INDEX `fk-NotaAp-Empleado_idx` (`carnet_docente` ASC) VISIBLE,
  INDEX `fk-NotaAp-Periodo_idx` (`id_periodo` ASC) VISIBLE,
  INDEX `fk-NotaAp-Aptitud_idx` (`id_aptitud` ASC) VISIBLE,
  CONSTRAINT `fk-NotaAp-Alumno`
    FOREIGN KEY (`carnet_alumno`)
    REFERENCES `expediente_fgk`.`alumno` (`carnet_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-NotaAp-Empleado`
    FOREIGN KEY (`carnet_docente`)
    REFERENCES `expediente_fgk`.`empleado` (`carnet_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-NotaAp-Periodo`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `expediente_fgk`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-NotaAp-Aptitud`
    FOREIGN KEY (`id_aptitud`)
    REFERENCES `expediente_fgk`.`aptitud` (`id_aptitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
